server:
  #  服务器端口
  port: 10000
spring:
  #  地址池配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/staffsync?useSSL=false&characterEncoding=utf-8
    username: root
    password: root
  # swagger策略配置
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    #是否启用
    enabled: true
    # 可以支持多个location, 用','隔开
    locations: classpath:db/migration
    #是否创建元数据表
    validate-on-migrate: true
    # flyway 的 clean 命令会删除指定 schema 下的所有 table, 生产务必禁掉。这个默认值是
    clean-disabled: true
    # 如果数据库不是空表，需要设置成 true，否则启动报错
    baseline-on-migrate: true
