server:
  #  服务器端口
  port: 10000
spring:
  #  地址池配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/staffsync?useSSL=false&characterEncoding=utf-8
    username: root
    password: root
  # flywat框架配置
  flyway:
    #是否启用
    enabled: true
    # 可以支持多个location, 用','隔开
    locations: classpath:db/migration
    #是否创建元数据表
    validate-on-migrate: true
    # flyway 的 clean 命令会删除指定 schema 下的所有 table, 生产务必禁掉。
    clean-disabled: true
    # 如果数据库不是空表，需要设置成 true，否则启动报错
    baseline-on-migrate: true
  mvc:
    pathmatch:
      # 路径匹配策略（用于swagger配置）
      matching-strategy: ant_path_matcher
# 鉴权配置
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: staffsync
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
# 日志配置
logging:
  config: classpath:logging/logback.xml
# springdoc配置
springdoc:
  swagger-ui:
    # 是否启用swagger-ui
    enabled: true
    path: /doc
  api-docs:
    path: /v3/api-docs
# knife4j配置
knife4j:
  # 增强功能，只使用ui可以将其关闭
  enable: false
  setting:
    language: zh_cn