package online.weiyin.staffsync;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.transaction.annotation.EnableTransactionManagement;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@EnableTransactionManagement
public class StaffsyncJavaApplication {

    public static void main(String[] args) {
        SpringApplication.run(StaffsyncJavaApplication.class, args);
    }

}
